Repository Namo-log/Server, pull requests merged in 2024-08, with the labels that each got.

#233 [Feature/232] 운영 서버를 위한 환경 설정 수정
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/swagger/SwaggerConfig.java
  docker/docker-compose-dev.yml
  docker/docker-compose-prod.yml
  storage/db-mysql/src/main/resources/mysql.yml
Labels: :wrench: chore, :recycle: refactor

#240 [Rollback/238] 개인 일정 기록 추가시 이미지 이름 복구
  .github/workflows/cd-dev-action.yml
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/controller/DiaryController.java
Labels: :art: style

#244 [Bug/243] 토큰 재발급시 헤더에 기존 토큰이 존재하는 경우 발생하는 에러 해결
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/SecurityConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/WebSecurityUrl.java
  storage/db-mysql-v2/src/main/resources/mysql.yml
Labels: :bug: bug

#252 :memo: Docs: Update README.md
  README.md
Labels: :memo: documentation

#251 [Refactor/246] V2 소셜 로그인 리팩토링
  .github/workflows/cd-dev-action.yml
  Dockerfile
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/Category/service/CategoryMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/api/AuthApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/TermController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/MemberConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/MemberResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/TermConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberDto.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/facade/AuthFacade.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/facade/TermFacade.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/KeyDecoder.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/MemberManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/MemberScheduler.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/SocialLoginService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/TermManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/config/security/SecurityConfig.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/config/security/WebSecurityUrl.java
  clients/social-client/build.gradle
  clients/social-client/src/main/java/com/namo/spring/client/social/apple/client/AppleAuthClient.java
  clients/social-client/src/main/java/com/namo/spring/client/social/apple/dto/AppleResponse.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/common/utils/DatabaseInitializer.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/entity/Palette.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/service/PaletteService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/entity/Notification.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/Activity.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/Diary.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Term.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/MemberRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/TermRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/TermService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/type/Content.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/type/MemberRole.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/type/MemberStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/type/SocialType.java
Labels: :art: style, :sparkles: feature, :wrench: chore, :recycle: refactor, ✨ feature

#254 [Feature/253] dev 서버 스웨거 V1, V2 분리
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/config/security/WebSecurityUrl.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/config/swagger/SwaggerConfig.java
  application/external-api-v2/src/main/resources/swagger.yml
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/WebSecurityUrl.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/swagger/SwaggerConfig.java
  application/external-api/src/main/resources/swagger.yml
Labels: :wrench: chore

#260 [Bug/259] Yaml 설정파일 특수문자 오타 제거
  storage/db-mysql-v2/src/main/resources/mysql.yml
Labels: :bug: bug

#261 [Bug/259] email nullable 허용
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
Labels: :bug: bug

#262 [bug/259] member 생성시 email 체크 해제
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/MemberManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/SocialLoginService.java
Labels: :bug: bug

#266 [Refactor/264] 소셜 로그인 최종 완료 추가 구현, OIDC 로직 개선
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/api/AuthApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/MemberConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/facade/AuthFacade.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/MemberManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/SocialLoginService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/TagGenerator.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/common/exception/ExceptionAdvice.java
  application/external-api-v2/src/main/resources/swagger.yml
  application/external-api-v2/src/test/java/com/namo/spring/application/external/api/user/service/TagGeneratorTest.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/MemberRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/MemberService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/type/MemberStatus.java
Labels: :sparkles: feature, :recycle: refactor, ✨ feature

#267 [Feature/247, 250] 개인/모임 일정 생성 , 모임 일정 목록 조회 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/Category/service/CategoryMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/service/CategoryMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/MeetingScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ParticipantConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/PersonalScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/PersonalScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/MemberManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MeetingValidationUtils.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MultipartJackson2HttpMessageConverter.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/facade/GroupFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/facade/MeetingDiaryFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/facade/MeetingScheduleFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/service/GroupAndUserService.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/service/AlarmService.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/service/CategoryService.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/service/ImageService.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/service/PaletteService.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/service/PeriodService.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/service/ScheduleService.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  core/core-common/src/main/java/com/namo/spring/core/common/exception/IndividualException.java
  core/core-common/src/main/java/com/namo/spring/core/common/exception/PersonalException.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/constant/FilePath.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/properties/ImageUrlProperties.java
  core/core-infra/src/main/resources/aws.yml
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/repository/CategoryRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/service/CategoryService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/type/ColorCategory.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/type/ColorChip.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/type/PaletteEnum.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleParticipantItemQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ScheduleRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ScheduleService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/type/ParticipantRole.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/type/ParticipateStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/type/ScheduleType.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/MemberService.java
  storage/db-mysql-v2/src/main/resources/db/magration/V1.0.0__Initial_schema.sql
  storage/db-mysql-v2/src/main/resources/mysql.yml
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/domains/individual/domain/Schedule.java
Labels: :sparkles: feature

#269 [Feature/268] 일정 생성 / 모임 목록 조회 API 리팩토링
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/MeetingScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ParticipantConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/common/security/filter/JwtExceptionFilter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MeetingValidationUtils.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/service/GroupAndUserService.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ScheduleRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ScheduleService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/type/ParticipantStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/FriendshipRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/MemberRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/MemberService.java
  storage/db-mysql-v2/src/test/java/com/namo/spring/db/mysql/domain/schedule/entity/ScheduleParticipantsUpdateTest.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#271 [Feature/248] 모임 초대자/ 참여자 월간 일정 조회 API V2 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/MeetingScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/common/MultipartJackson2HttpMessageConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/Converter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MeetingParticipantValidationUtils.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/SchedulePeriodValidationUtils.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  core/core-common/src/main/java/com/namo/spring/core/common/utils/DateUtil.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/type/PaletteEnum.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleParticipantItemQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleParticipantQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/type/Period.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/FriendshipRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
Labels: :sparkles: feature

#277 [Feature/273] 모임 일정 상세 조회 / 수정 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/MeetingScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipationActionManager.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MeetingParticipantValidationUtils.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleParticipantQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/exception/ParticipantException.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/User.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/FriendshipRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
  storage/db-mysql-v2/src/test/java/com/namo/spring/db/mysql/domain/schedule/entity/ScheduleParticipantsUpdateTest.java
Labels: :sparkles: feature
