Repository Namo-log/Server, pull requests merged in 2024-09, with the labels that each got.

#279 [Feature/278] 개인(나의/친구) 월간 일정 조회 API V2 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/notification/service/NotificationManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/DiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/MeetingScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/PersonalScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/PersonalScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/SchedulePeriodValidationUtils.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/entity/Category.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/dto/ScheduleNotificationQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/entity/Notification.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/repository/NotificationRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/service/NotificationService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleParticipantQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/FriendshipRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
Labels: :sparkles: feature

#284 [Feature/283] 일기 보관함 캘린더 조회 관련 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/DiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/DiaryResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/DiaryRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/DiaryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/DiaryImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/DiaryManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/DiaryUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/constant/FilePath.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
Labels: :art: style, :sparkles: feature, :recycle: refactor

#287 [Feature/286] 일기 조회시 상단 스케줄 정보 조회를 위한 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/ScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/LocationConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/ScheduleUsecase.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
Labels: :sparkles: feature, :recycle: refactor, ✨ feature

#290 [Refactor/288] 일기 관련 DTO 변경 사항 적용
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/DiaryResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/DiaryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/ScheduleUsecase.java
  storage/db-mysql-v2/src/main/resources/mysql.yml
Labels: :art: style, :recycle: refactor

#292 [Refactor/291] 기록 상단 스케줄 조회 시 일기 존재 여부 정보 추가
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleResponse.java
Labels: :art: style, :recycle: refactor

#293 [Hotfix] 스케줄이 조회되지 않는 버그 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/ScheduleController.java
Labels: :bug: bug

#296 [Feature/272] 게스트 초대 / 게스트 모임 가입 API구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/controller/GuestController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/converter/GuestMeetingResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/converter/GuestParticipantResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/dto/GuestMeetingResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/dto/GuestParticipantRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/dto/GuestParticipantResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/service/GuestManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/usecase/GuestUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/MeetingScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/ScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/LocationConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipationActionManager.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/PersonalScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/ScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/MemberConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/facade/AuthFacade.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/MemberManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/TagGenerator.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/config/security/SecurityConfig.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/config/security/WebSecurityUrl.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MeetingParticipantValidationUtils.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/repository/CategoryRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/dto/AnonymousInviteCodeQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Anonymous.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/exception/AnonymousException.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/AnonymousRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/AnonymousService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/type/Password.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.0.1__Add_palette_column_to_member_table.sql
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.0.2__Add_And_Modify_columns_to_anonymous_table.sql
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.0.3__Modify_anonymous_column_from_participant_table.sql
  storage/db-mysql-v2/src/main/resources/mysql.yml
  storage/db-mysql/src/main/resources/mysql.yml
Labels: :sparkles: feature, :recycle: refactor

#306 [Feature/300] 일기(다이어리) 삭제 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/DiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/DiaryImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/DiaryManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/DiaryUseCase.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/Diary.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/DiaryService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
Labels: :sparkles: feature, :recycle: refactor

#308 [Feature/307] 카테고리 조회 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/controller/CategoryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/converter/CategoryConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/dto/CategoryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/service/CategoryManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/usecase/CategoryUseCase.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/repository/CategoryRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/service/CategoryService.java
Labels: :sparkles: feature

#309 [Feature/297] 요구 사항 변경에 따른 custom 일정 정보 적용 및 수정 API구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/controller/GuestController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/converter/GuestMeetingResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/converter/GuestParticipantResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/dto/GuestMeetingResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/dto/GuestParticipantResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/service/GuestManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/usecase/GuestUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/DiaryResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/MeetingScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/PersonalScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/config/properties/WebUrlConfig.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MeetingParticipantValidationUtils.java
  application/external-api-v2/src/main/resources/application.yml
  application/external-api-v2/src/main/resources/web.yml
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleParticipantQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleSummaryQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.0.6__Drop_invitation_url_column_from_schedule_table.sql
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.0.7__Add_columns_to_participant_table.sql
  storage/db-mysql-v2/src/main/resources/mysql.yml
Labels: :sparkles: feature

#310 [Feature/307] 카테고리 관리 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/controller/CategoryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/converter/CategoryConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/dto/CategoryRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/dto/CategoryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/service/CategoryMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/service/CategoryManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/usecase/CategoryUseCase.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/entity/Category.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/service/CategoryService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
Labels: :sparkles: feature

#312 [Feature/311] 모임 기록 중 활동을 생성하는 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityImageConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityParticipantConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/ActivityRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/ActivityResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/ActivityUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MeetingParticipantValidationUtils.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/Activity.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/ActivityImage.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/ActivityParticipant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/ActivityImageService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/ActivityUserService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.0.8__Add_columns_to_activity_table.sql
  storage/db-mysql-v2/src/main/resources/mysql.yml
Labels: :sparkles: feature

#314 [Feature/313] 날짜별 기록 정보 조회에 ScheduleID 값 추가 + 짜잘한 예외처리 및 버그 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/controller/CategoryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/DiaryResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/DiaryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/ActivityUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/DiaryUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/ScheduleUsecase.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor, ✨ feature

#319 [Refactor/318] 유지보수성 개선을 위한 통일
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/controller/GuestController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/api/S3Api.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/controller/S3Controller.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/DiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/MeetingScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/ScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/api/AuthApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/TermController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/TagGenerator.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/SocialUtils.java
  build.gradle
  storage/db-redis/src/test/java/com/namo/spring/db/redis/config/RedisTestContainerConfig.java
Labels: :recycle: refactor

#321 [Feature/320] 활동 삭제 API 구현 + 활동이미지,기록 이미지 로직 추상화 리팩토링
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/DiaryImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/DiaryManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/AbstractImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/ActivityImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/DiaryImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/ImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/ActivityUseCase.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/utils/SocialUtils.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/aws/s3/FileUtils.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/ActivityImageService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/ActivityService.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor, ✨ feature

#326 [Feature/325] 친구관련 기능 구현 (+ 유저 조회로직 구분)
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/usecase/CategoryUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/service/GuestManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/PersonalScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/ScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/FriendController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/FriendshipConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/FriendshipResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/facade/AuthFacade.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/scheduler/MemberScheduler.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/FriendManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/MemberManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/usecase/FriendUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/FriendshipValidator.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/NicknameTag.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/TagGenerator.java
  application/external-api-v2/src/test/java/com/namo/spring/application/external/api/user/service/TagGeneratorTest.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Friendship.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/FriendshipRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/MemberRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/MemberService.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.0.9__Add_columns_to_member_table.sql
Labels: :sparkles: feature, :recycle: refactor, ✨ feature

#328 [Feature/327] 상단 스케줄 조회에 참여자 정보, 명수 추가 (+ 모임 수락시 즉시 참여 변경)
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipationActionManager.java
Labels: :bug: bug, :sparkles: feature, ✨ feature

#330 [Bug/329] 활동 조회에 이미지값 누락 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/ActivityResponse.java
Labels: :bug: bug

#333 [Bug Fix/332] 개인 일정 수정 dto에 누락된 카테고리 필드 추가
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
Labels: :bug: bug

#335 [Refactor/334] 월간 일정 조회 방식에서 기간을 선택하여 조회하는 방식으로 변경
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/controller/GuestController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/usecase/GuestUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/PersonalScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/PersonalScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/SchedulePeriodValidationUtils.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/FriendshipRepository.java
Labels: :recycle: refactor

#339 [bug/336] 스케줄 상단 조회에 대해 참여자 정보가 누락되어 표현되지 않는 버그 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleResponseConverter.java
Labels: :bug: bug

#338 [Feature/337] 일정 삭제 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/ScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/ScheduleUsecase.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
Labels: :sparkles: feature

#340 [Feature/331] 모임 참여자 수락/비수락 상태 제거
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/service/GuestManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/notification/service/NotificationManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/ScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ParticipantConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipationActionManager.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/PersonalScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/ScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/FriendManageService.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/type/ParticipantStatus.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.1.3__Drop_status_column_from_participant_table.sql
  storage/db-mysql-v2/src/test/java/com/namo/spring/db/mysql/domain/schedule/entity/ScheduleParticipantsUpdateTest.java
Labels: :sparkles: feature, :recycle: refactor

#345 [Feature/341] 활동 수정 기능 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/ActivityRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/ActivityImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/DiaryImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/ActivityUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/SchedulePeriodValidationUtils.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/Activity.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/ActivityParticipant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/repository/ActivityParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/ActivityUserService.java
Labels: :bug: bug, :art: style, ✨ feature

#344 [Feature/342] 모임 나가기 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/usecase/GuestUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/PersonalScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/PeriodValidationUtils.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
Labels: :bug: bug, :sparkles: feature
