Repository Namo-log/Server, pull requests merged in 2024-11, with the labels that each got.

#403 [Feature/402] 모임 목록 조회시에 기록 존재 여부 필드 -> 기록or활동 존재 여부로 변경
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleSummaryQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/ParticipantService.java
Labels: :sparkles: feature

#407 [Refactor/406] 개인/생일 일정 생성 시 participant 정보도 업데이트 되도록 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/facade/AuthFacade.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.1.6__Modify_columns_from_schedule_table.sql
Labels: :recycle: refactor, ✨ feature

#405 [Feature/404] S3 멀티파트 업로드를 위한 Presigned URL 생성 및 완료 요청 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/controller/S3Controller.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/aws/dto/MultipartCompleteRequest.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/aws/dto/MultipartStartResponse.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/aws/s3/S3Uploader.java
Labels: :sparkles: feature, :recycle: refactor, ✨ feature

#410 [Bug Fix] 모임 목록 조회 시 중복되는 데이터가 조회되는 오류 수정
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
Labels: :bug: bug

#414 [Feature/413] "모임 활동 조회" API 캐시 적용
  application/external-api-v2/src/main/java/com/namo/spring/NamoApplication.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/ActivityResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/ActivityManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/ActivityUseCase.java
  storage/db-mysql-v2/build.gradle
  storage/db-redis/src/main/java/com/namo/spring/db/redis/config/RedisConfig.java
Labels: :sparkles: feature, :wrench: chore, :recycle: refactor

#418 [Feature/417] 프로필 설정 기능 구현 + hot fix
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/ProfileController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/ProfileConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/ProfileRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/ProfileResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/usecase/ProfileUseCase.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/model/query/ScheduleSummaryQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Anonymous.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/utils/UserValidationUtils.java
Labels: :recycle: refactor, ✨ feature
