Repository Namo-log/Server, pull requests merged in 2024-04, with the labels that each got.

#65 [Feature/64]: 이미지 삭제 시 s3에 이미지도 삭제
  src/main/java/com/example/namo2/domain/schedule/application/ScheduleFacade.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/ImageService.java
  src/main/java/com/example/namo2/domain/schedule/dao/repository/ImageRepository.java
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
Labels: :sparkles: feature

#63 [Feature/62] 로그인시 새로운 유저인지 판별하는 필드 추가
  src/main/java/com/example/namo2/domain/category/dao/repository/CategoryRepository.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimAndUserRepository.java
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/domain/user/application/converter/UserResponseConverter.java
  src/main/java/com/example/namo2/domain/user/ui/AuthController.java
  src/main/java/com/example/namo2/domain/user/ui/dto/UserResponse.java
  src/main/java/com/example/namo2/global/utils/JwtUtils.java
Labels: :sparkles: feature

#69 :bug: Fix: JarLauncher 에러 픽스
  Dockerfile
  src/main/java/com/example/namo2/domain/test/ui/TestController.java
  src/main/java/com/example/namo2/domain/test/ui/dto/TestResponse.java
  src/main/java/com/example/namo2/global/logging/filter/ApiLoggingFilter.java
  src/main/resources/application-dev.yml
Labels: :bug: bug, :sparkles: feature

#72 [Feat] 모임 스케줄 Validation 검증 로직 및 비기능 개발
  src/main/java/com/example/namo2/domain/category/application/impl/CategoryService.java
  src/main/java/com/example/namo2/domain/memo/application/MoimMemoFacade.java
  src/main/java/com/example/namo2/domain/moim/application/MoimScheduleFacade.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleAndUserService.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimService.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimRepository.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleRepository.java
  src/main/java/com/example/namo2/domain/moim/ui/MoimScheduleController.java
  src/main/java/com/example/namo2/domain/user/application/impl/UserService.java
  src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
  src/main/java/com/example/namo2/global/utils/Converter.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#73 [Feature/66] User validation 처리
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/domain/user/application/converter/UserConverter.java
  src/main/java/com/example/namo2/domain/user/application/impl/UserService.java
  src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleFeignException.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoFeignClientExceptionDecoder.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverFeignException.java
  src/main/java/com/example/namo2/global/utils/SocialUtils.java
Labels: :recycle: refactor

#76 [Feature/75] 일정 validation처리
  src/main/java/com/example/namo2/domain/category/application/impl/CategoryService.java
  src/main/java/com/example/namo2/domain/schedule/application/ScheduleFacade.java
  src/main/java/com/example/namo2/domain/schedule/application/converter/ScheduleConverter.java
  src/main/java/com/example/namo2/domain/schedule/application/converter/ScheduleResponseConverter.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/AlarmService.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/PeriodService.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/ScheduleService.java
  src/main/java/com/example/namo2/domain/schedule/dao/repository/ScheduleRepositoryImpl.java
  src/main/java/com/example/namo2/domain/schedule/domain/Location.java
  src/main/java/com/example/namo2/domain/schedule/domain/Schedule.java
  src/main/java/com/example/namo2/domain/schedule/ui/ScheduleController.java
  src/main/java/com/example/namo2/domain/schedule/ui/dto/ScheduleRequest.java
  src/main/java/com/example/namo2/domain/schedule/ui/dto/ScheduleResponse.java
  src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
Labels: :sparkles: feature, :recycle: refactor

#77 [Feature/74] 모임 조회시 개인 커스텀 이름으로 조회하게끔 변경
  src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java
  src/main/java/com/example/namo2/domain/moim/application/converter/MoimResponseConverter.java
Labels: :sparkles: feature

#83 [Fature/82] 스웨거 동작 오류 해결
  src/main/java/com/example/namo2/global/config/interceptor/InterceptorConfig.java
  src/main/java/com/example/namo2/global/logging/filter/ApiLoggingFilter.java
Labels: :bug: bug, :memo: documentation

#84 [Feature/82] 스웨거 패키지 스캔 관련 설정 수정
  src/main/java/com/example/namo2/global/logging/filter/ApiLoggingFilter.java
  src/main/resources/application-docs.yml
Labels: :bug: bug, :memo: documentation

#89 [Feature/88] Cors 문제 해결
  src/main/java/com/example/namo2/global/config/logging/ApiLoggingFilter.java
  src/main/java/com/example/namo2/global/config/web/CorsFilter.java
Labels: :bug: bug, :sparkles: feature

#91 [Feature/90] Swagger api test 환경 구축
  src/main/java/com/example/namo2/domain/category/ui/CategoryController.java
  src/main/java/com/example/namo2/domain/memo/ui/MoimMemoController.java
  src/main/java/com/example/namo2/domain/moim/ui/MoimController.java
  src/main/java/com/example/namo2/domain/moim/ui/MoimScheduleController.java
  src/main/java/com/example/namo2/domain/schedule/ui/ScheduleController.java
  src/main/java/com/example/namo2/domain/test/ui/TestController.java
  src/main/java/com/example/namo2/domain/user/ui/AuthController.java
  src/main/java/com/example/namo2/global/annotation/swagger/ApiErrorCode.java
  src/main/java/com/example/namo2/global/annotation/swagger/ApiErrorCodes.java
  src/main/java/com/example/namo2/global/config/properties/ExampleHolder.java
  src/main/java/com/example/namo2/global/config/swagger/SwaggerConfig.java
  src/main/resources/application-docs.yml
Labels: :memo: documentation, :sparkles: feature, :test_tube: test

#93 [Feature/92] API 버저닝 준비 및 url 수정
  src/main/java/com/example/namo2/domain/category/ui/CategoryController.java
  src/main/java/com/example/namo2/domain/memo/ui/GroupDiaryController.java
  src/main/java/com/example/namo2/domain/moim/ui/GroupController.java
  src/main/java/com/example/namo2/domain/moim/ui/GroupScheduleController.java
  src/main/java/com/example/namo2/domain/schedule/ui/DiaryController.java
  src/main/java/com/example/namo2/domain/schedule/ui/ScheduleController.java
  src/main/java/com/example/namo2/domain/test/ui/TestController.java
  src/main/java/com/example/namo2/domain/user/ui/AuthController.java
  src/main/java/com/example/namo2/domain/user/ui/TermController.java
  src/main/java/com/example/namo2/global/config/swagger/SwaggerConfig.java
  src/main/resources/application-docs.yml
Labels: :memo: documentation, :art: style, :sparkles: feature
