Repository Namo-log/Server, pull requests merged in 2024-05, with the labels that each got.

#99 [Feature/97] Request & Response 파라미터명 변경
  src/main/java/com/example/namo2/domain/group/application/MoimFacade.java
  src/main/java/com/example/namo2/domain/group/application/MoimMemoFacade.java
  src/main/java/com/example/namo2/domain/group/application/MoimScheduleFacade.java
  src/main/java/com/example/namo2/domain/group/application/converter/GroupResponseConverter.java
  src/main/java/com/example/namo2/domain/group/application/converter/MoimDiaryResponseConverter.java
  src/main/java/com/example/namo2/domain/group/application/converter/MoimMemoLocationConverter.java
  src/main/java/com/example/namo2/domain/group/application/converter/MoimScheduleConverter.java
  src/main/java/com/example/namo2/domain/group/application/converter/MoimScheduleResponseConverter.java
  src/main/java/com/example/namo2/domain/group/dao/repository/schedule/MoimScheduleAndUserRepositoryImpl.java
  src/main/java/com/example/namo2/domain/group/domain/Moim.java
  src/main/java/com/example/namo2/domain/group/domain/MoimSchedule.java
  src/main/java/com/example/namo2/domain/group/domain/MoimScheduleAndUser.java
  src/main/java/com/example/namo2/domain/group/domain/MoimScheduleStatus.java
  src/main/java/com/example/namo2/domain/group/domain/MoimStatus.java
  src/main/java/com/example/namo2/domain/group/domain/constant/MoimScheduleStatus.java
  src/main/java/com/example/namo2/domain/group/domain/constant/MoimStatus.java
  src/main/java/com/example/namo2/domain/group/domain/constant/VisibleStatus.java
  src/main/java/com/example/namo2/domain/group/ui/GroupController.java
  src/main/java/com/example/namo2/domain/group/ui/GroupDiaryController.java
  src/main/java/com/example/namo2/domain/group/ui/GroupScheduleController.java
  src/main/java/com/example/namo2/domain/group/ui/dto/GroupDiaryRequest.java
  src/main/java/com/example/namo2/domain/group/ui/dto/GroupDiaryResponse.java
  src/main/java/com/example/namo2/domain/group/ui/dto/GroupRequest.java
  src/main/java/com/example/namo2/domain/group/ui/dto/GroupResponse.java
  src/main/java/com/example/namo2/domain/group/ui/dto/GroupScheduleRequest.java
  src/main/java/com/example/namo2/domain/group/ui/dto/GroupScheduleResponse.java
  src/main/java/com/example/namo2/domain/individual/application/DiaryFacade.java
  src/main/java/com/example/namo2/domain/individual/application/ScheduleFacade.java
  src/main/java/com/example/namo2/domain/individual/application/converter/DiaryResponseConverter.java
  src/main/java/com/example/namo2/domain/individual/application/converter/ScheduleResponseConverter.java
  src/main/java/com/example/namo2/domain/individual/application/impl/ScheduleService.java
  src/main/java/com/example/namo2/domain/individual/dao/repository/schedule/ScheduleRepositoryCustom.java
  src/main/java/com/example/namo2/domain/individual/dao/repository/schedule/ScheduleRepositoryImpl.java
  src/main/java/com/example/namo2/domain/individual/ui/CategoryController.java
  src/main/java/com/example/namo2/domain/individual/ui/DiaryController.java
  src/main/java/com/example/namo2/domain/individual/ui/ScheduleController.java
  src/main/java/com/example/namo2/domain/individual/ui/dto/DiaryRequest.java
  src/main/java/com/example/namo2/domain/individual/ui/dto/DiaryResponse.java
  src/main/java/com/example/namo2/domain/individual/ui/dto/MoimCategoryDto.java
Labels: :art: style, :recycle: refactor

#102 [Feature/101] 이미지 저장 로직 수정
  build.gradle
  src/main/java/com/example/namo2/domain/group/application/MoimFacade.java
  src/main/java/com/example/namo2/domain/group/application/MoimMemoFacade.java
  src/main/java/com/example/namo2/domain/individual/application/DiaryFacade.java
  src/main/java/com/example/namo2/global/common/constant/FilePath.java
  src/main/java/com/example/namo2/global/config/interceptor/InterceptorConfig.java
  src/main/java/com/example/namo2/global/utils/FileUtils.java
  src/main/java/com/example/namo2/global/utils/S3Uploader.java
Labels: :bug: bug, :sparkles: feature

#104 [Feature/103] 스웨거 test 환경 구축
  src/main/java/com/example/namo2/domain/group/ui/GroupController.java
  src/main/java/com/example/namo2/domain/group/ui/GroupDiaryController.java
  src/main/java/com/example/namo2/domain/individual/ui/DiaryController.java
  src/main/java/com/example/namo2/global/utils/JwtUtils.java
Labels: :bug: bug, :memo: documentation, :sparkles: feature

#106 [Feature/105] 스웨거 설명 수정
  src/main/java/com/example/namo2/domain/group/ui/GroupController.java
  src/main/java/com/example/namo2/domain/group/ui/GroupDiaryController.java
  src/main/java/com/example/namo2/domain/group/ui/GroupScheduleController.java
  src/main/java/com/example/namo2/domain/individual/ui/CategoryController.java
  src/main/java/com/example/namo2/domain/individual/ui/DiaryController.java
  src/main/java/com/example/namo2/domain/individual/ui/ScheduleController.java
  src/main/java/com/example/namo2/domain/user/ui/AuthController.java
  src/main/java/com/example/namo2/domain/user/ui/TermController.java
Labels: :memo: documentation

#108 [feature/107] Multipart/from-data logging 기능 추가
  src/main/java/com/example/namo2/global/config/logging/ApiLoggingFilter.java
Labels: :memo: documentation, :sparkles: feature

#114 [Feature/110] 회원 탈퇴 Jwt 토큰 로직 수정
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoAuthClient.java
  src/main/java/com/example/namo2/global/utils/JwtUtils.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#113 [Feature/112] 모임 기록 삭제(그룹) api 파라미터 변경
  src/main/java/com/example/namo2/domain/group/application/MoimMemoFacade.java
  src/main/java/com/example/namo2/domain/group/application/MoimScheduleFacade.java
  src/main/java/com/example/namo2/domain/group/application/impl/MoimMemoService.java
  src/main/java/com/example/namo2/domain/group/dao/repository/diary/MoimMemoRepository.java
  src/main/java/com/example/namo2/domain/group/ui/GroupDiaryController.java
  src/main/java/com/example/namo2/domain/individual/application/DiaryFacade.java
  src/main/java/com/example/namo2/domain/individual/application/ScheduleFacade.java
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/global/config/logging/ApiLoggingFilter.java
  src/main/java/com/example/namo2/global/utils/FileUtils.java
Labels: :bug: bug, :sparkles: feature

#116 [feature/115] 월간 기록 조회 이슈 해결
  src/main/java/com/example/namo2/domain/individual/ui/DiaryController.java
Labels: :bug: bug, :sparkles: feature

#121 [feature/120] 개인이 삭제한 모임 일정이 타 모임 캘린더에서 보이는 오류 수정
  src/main/java/com/example/namo2/domain/individual/dao/repository/schedule/ScheduleRepositoryImpl.java
Labels: :sparkles: feature

#124 [Feature/123] commit lint 검사기 구현
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.ts
  package-lock.json
  package.json
  yarn.lock
Labels: :art: style, :sparkles: feature

#125 [feature/117] 모임 기록 상세 조회 api 구현
  src/main/java/com/example/namo2/domain/group/application/MoimMemoFacade.java
  src/main/java/com/example/namo2/domain/group/application/converter/MoimDiaryResponseConverter.java
  src/main/java/com/example/namo2/domain/group/application/impl/MoimMemoLocationService.java
  src/main/java/com/example/namo2/domain/group/application/impl/MoimScheduleAndUserService.java
  src/main/java/com/example/namo2/domain/group/ui/GroupDiaryController.java
Labels: :sparkles: feature

#128 [feature/126] 유저 로그인에 약관 동의 반환값 추가
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/domain/user/application/converter/TermConverter.java
  src/main/java/com/example/namo2/domain/user/application/converter/UserResponseConverter.java
  src/main/java/com/example/namo2/domain/user/application/impl/UserService.java
  src/main/java/com/example/namo2/domain/user/dao/repository/TermRepository.java
  src/main/java/com/example/namo2/domain/user/ui/dto/UserResponse.java
Labels: :sparkles: feature

#129 [feature/127] 회원탈퇴 로직 변경
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/domain/user/application/converter/UserConverter.java
  src/main/java/com/example/namo2/domain/user/application/impl/UserService.java
  src/main/java/com/example/namo2/domain/user/dao/repository/UserRepository.java
  src/main/java/com/example/namo2/domain/user/domain/User.java
  src/main/java/com/example/namo2/domain/user/domain/constant/SocialType.java
  src/main/java/com/example/namo2/domain/user/ui/AuthController.java
  src/main/java/com/example/namo2/domain/user/ui/dto/UserRequest.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleAuthApi.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleAuthClient.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleResponse.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoAuthApi.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoAuthClient.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoResponse.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoUnlinkApi.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverAuthApi.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverAuthClient.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverOpenApi.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverResponse.java
Labels: :sparkles: feature, :recycle: refactor

#118 [Feature/95] 일정 컨트롤러 테스트 코드 작성
  build.gradle
  src/main/java/com/example/namo2/domain/individual/ui/dto/ScheduleRequest.java
  src/test/java/com/example/namo2/domain/individual/ui/ScheduleControllerTest.java
Labels: :sparkles: feature
