Repository Namo-log/Server, pull requests merged in 2024-12, with the labels that each got.

#420 [Feature/419] 모임 일정 초대하기 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/MeetingParticipantValidationUtils.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/type/ColorChip.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
Labels: :sparkles: feature, :recycle: refactor

#422 [Refactor/421] Redis 직렬화/역직렬화 리팩토링
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/ActivityResponse.java
  storage/db-mysql-v2/build.gradle
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/model/dto/FriendBirthdayListDto.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
  storage/db-redis/build.gradle
  storage/db-redis/src/main/java/com/namo/spring/db/redis/config/RedisConfig.java
Labels: :recycle: refactor

#424 [Feature/423]원본 -> 리사이징 이미지 변환 기능 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/scheduler/ImageResizingScheduler.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/service/ImageCacheService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/util/ImageKeyParser.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/AbstractImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/ActivityImageManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/serivce/image/DiaryImageManageService.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/config/AwsS3Config.java
  core/core-infra/src/main/resources/aws.yml
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/DiaryImageService.java
  storage/db-redis/src/main/java/com/namo/spring/db/redis/util/RedisUtil.java
Labels: :sparkles: feature

#426 [Feature/425] 포인트 충전 요청 및 관리자 기능 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/controller/CategoryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/point/controller/AdminPointController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/point/controller/MemberPointController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/point/converter/PointTransactionConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/point/dto/PointResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/point/service/PointManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/point/service/PointTransactionManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/point/usecase/PointChargeUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/controller/DiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/ScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/FriendController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/TermController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/UserController.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/entity/Point.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/entity/PointTransaction.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/enums/TransactionStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/enums/TransactionType.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/event/PointEventListener.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/exception/PointException.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/repository/PointRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/repository/PointTransactionRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/point/service/PointTransactionService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/event/MemberCreatedEvent.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/MemberService.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.1.7__Add_point_entity.sql
  storage/db-mysql-v2/src/main/resources/mysql.yml
Labels: :sparkles: feature
