Repository Namo-log/Server, pull requests merged in 2024-06, with the labels that each got.

#133 [Feature/132] docker-compose 구축
  docker/docker-compose-dev.yml
  docker/docker-compose-prod.yml
  docker/nginx/nginx.conf
Labels: :construction_worker: ci/cd

#149 [Feature/148] 환경변수 설정 정리
  application/external-api/build.gradle
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/facade/MoimFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/facade/MoimMemoFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/facade/MoimScheduleFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/facade/DiaryFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/facade/ScheduleFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/facade/UserFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/amazon/AmazonS3Config.java
  application/external-api/src/main/resources/application-db.yml
  application/external-api/src/main/resources/application-dev.yml
  application/external-api/src/main/resources/application-docs.yml
  application/external-api/src/main/resources/application-local.yml
  application/external-api/src/main/resources/application-prod.yml
  application/external-api/src/main/resources/application.yml
  application/external-api/src/main/resources/auth.yml
  application/external-api/src/main/resources/swagger.yml
  core/core-common/build.gradle
  core/core-infra/build.gradle
  core/core-infra/src/main/java/com/namo/spring/core/infra/Main.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/aws/s3/FileUtils.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/aws/s3/S3Uploader.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/constant/FilePath.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/config/AwsS3Config.java
  core/core-infra/src/main/resources/aws.yml
  storage/db-mysql/build.gradle
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/MysqlPackageLocation.java
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/config/JpaConfig.java
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/config/MysqlSourceConfig.java
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/domains/JpaPackageLocation.java
  storage/db-mysql/src/main/resources/mysql.yml
  storage/db-redis/build.gradle
  storage/db-redis/src/main/java/com/namo/spring/db/redis/config/RedisConfig.java
Labels: :recycle: refactor

#150 [Feat] Flyway 적용
  storage/README.md
  storage/db-mysql/build.gradle
  storage/db-mysql/src/main/resources/db/migration/V1.0.0__Initial_schema.sql
  storage/db-mysql/src/main/resources/mysql.yml
Labels: :sparkles: feature, :wrench: chore
