Repository Namo-log/Server, pull requests merged in 2024-10, with the labels that each got.

#349 [Feature/343] 스케줄에 대한 전체 활동 정산보기 기능구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/service/GuestManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/enums/DiaryFilter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/ScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ParticipantManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/ScheduleUsecase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/facade/AuthFacade.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/MemberManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/TagGenerator.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/PeriodValidationUtils.java
  application/external-api-v2/src/test/java/com/namo/spring/application/external/api/user/service/TagGeneratorTest.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/service/SettlementCalculator.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/NicknameTag.java
Labels: :sparkles: feature, ✨ feature

#354 [Refactor/353] 일정 시작일/종료일 자료형 LocalDateTime으로 변경
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/LocationConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/PersonalScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/interfaces/LocationDtoInterface.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/interfaces/PeriodDtoInterface.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/PeriodValidationUtils.java
Labels: :recycle: refactor

#358 [Document/357] 스웨거 컨트롤러 넘버링 명세 작업
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/category/controller/CategoryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/guest/controller/GuestController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/controller/S3Controller.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/ActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/Controller/DiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/api/PersonalScheduleApi.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/PersonalScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/controller/ScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/FriendController.java
Labels: :memo: documentation

#363 [Feature/362] 로그인/회원가입/토큰 재발급 response에 userid 추가
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/MemberConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/MemberResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/MemberResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/facade/AuthFacade.java
Labels: :sparkles: feature

#367 [bug/366] 모임 스케줄 수정시 버그 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
Labels: :bug: bug

#369 [Bug Fix/368] 방장 모임 일정 수정 시, 커스텀 정보 수정 로직 추가
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/usecase/MeetingScheduleUsecase.java
Labels: :bug: bug, :art: style

#360 [Feature/359] 나의 선호 색상 수정 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/UserController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/usecase/UserUseCase.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
Labels: :sparkles: feature, ✨ feature

#371 [Feature/370] 커버 이미지 업로드용 Prefix 등록
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/controller/S3Controller.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/constant/FilePath.java
Labels: :sparkles: feature, ✨ feature

#373 [Feature/372] API 스펙 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/ActivityResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleResponse.java
Labels: :sparkles: feature

#375 [Feature/374] 프로필 이미지 Prefix 추가 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/image/controller/S3Controller.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/constant/FilePath.java
Labels: :sparkles: feature

#377 [Hotfix/376] 활동조회 DTO 값 버그 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/ActivityResponseConverter.java
Labels: :bug: bug

#379 [Bug/378] 정산 정보 미생성 버그 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/usecase/ActivityUseCase.java
Labels: :bug: bug

#381 [Feature/380] 일정 생성 시 위치 정보 null 허용 수정
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/service/ScheduleManageService.java
Labels: :recycle: refactor

#383 [Feature/382] 나의 친구목록을 조회하는 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/FriendController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/FriendshipConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/FriendshipResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/FriendManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/usecase/FriendUseCase.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/FriendshipRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
Labels: :sparkles: feature, :recycle: refactor

#385 [Feature/384] 친구 즐겨찾기(선호친구) 등록/해제 기능 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/FriendController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/FriendshipConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/FriendshipResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/FriendManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/usecase/FriendUseCase.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Friendship.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/repository/FriendshipRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
Labels: :art: style, :sparkles: feature, :recycle: refactor, ✨ feature

#393 [Featrue/392] 스케줄 상단 조회시 종료 일자 추가 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/ScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/ScheduleResponse.java
Labels: :sparkles: feature

#390 [Feature/389] 친구 삭제 API 구현 완료
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/FriendController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/service/FriendManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/usecase/FriendUseCase.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/service/FriendshipService.java
Labels: :sparkles: feature

#395 [Refactor/394] 기록을 스케줄 타입별로 분리하여 Return
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/converter/DiaryResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/record/dto/DiaryResponse.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
Labels: :recycle: refactor

#396 [Feature/391] 기기 등록 / 푸시 알림 설정 조회 & 수정 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/notification/converter/DeviceConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/notification/service/NotificationMaker.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/notification/service/NotificationManageService.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/notification/service/NotificationMessageGenerator.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/PersonalScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/UserController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/NotificationResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/NotificationRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/NotificationResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/usecase/UserUseCase.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/annotation/validation/ReminderTimesValidator.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/config/properties/ReminderTimeConfig.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/DeviceTypeValidationUtil.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/global/utils/ReminderTimeUtils.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/repository/DeviceRepository.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/service/DeviceService.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/type/NotificationType.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/notification/type/ReceiverDeviceType.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.1.4__Add_notification_status_column_to_member_table.sql
Labels: :sparkles: feature, :recycle: refactor

#399 [Feature/398] 모임 일정 목록 조회 dto에 기록 작성 여부 추가
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/converter/MeetingScheduleResponseConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/schedule/dto/MeetingScheduleResponse.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/dto/ScheduleSummaryQuery.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/repository/ParticipantRepository.java
Labels: ✨ feature

#400 [Feature/346] member 테이블에 회원가입 완료일 컬럼 추가
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
  storage/db-mysql-v2/src/main/resources/db/migration/dev/V1.1.5__Add_signupat_column_to_member_table.sql
Labels: :sparkles: feature, ✨ feature

#401 [Feature/397] 친구의 카테고리 정보를 조회하는 API 구현
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/controller/FriendController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/converter/FriendCategoryConverter.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/dto/FriendCategoryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/user/usecase/FriendUseCase.java
Labels: :sparkles: feature
