Repository Namo-log/Server, pull requests merged in 2024-03, with the labels that each got.

#29 [Feature/25] issue 및 pr 라벨링 자동화
  .github/ISSUE_TEMPLATE/⛔️-bug.md
  .github/ISSUE_TEMPLATE/✅-task.md
  .github/ISSUE_TEMPLATE/❓question.md
  .github/github-label-config.yml
  .github/labeler-config.yml
  .github/pull_request_template.md
  .github/workflows/auto-labeler.yml
Labels: :sparkles: feature

#30 [Feature/26] issue assignees 할당 자동화
  .github/workflows/issue-assigner.yml
Labels: :sparkles: feature, :wrench: chore

#21 [Feature/14] Memo Domain Refactoring
  src/main/java/com/example/namo2/domain/memo/MoimMemoLocationRepositoryCustom.java
  src/main/java/com/example/namo2/domain/memo/MoimMemoLocationRepositoryImpl.java
  src/main/java/com/example/namo2/domain/memo/MoimMemoService.java
  src/main/java/com/example/namo2/domain/memo/application/MoimMemoFacade.java
  src/main/java/com/example/namo2/domain/memo/application/converter/MoimMemoConverter.java
  src/main/java/com/example/namo2/domain/memo/application/converter/MoimMemoLocationConverter.java
  src/main/java/com/example/namo2/domain/memo/application/converter/MoimMemoResponseConverter.java
  src/main/java/com/example/namo2/domain/memo/application/impl/MoimMemoLocationService.java
  src/main/java/com/example/namo2/domain/memo/application/impl/MoimMemoService.java
  src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoLocationAndUserRepository.java
  src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoLocationImgRepository.java
  src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoLocationRepository.java
  src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoLocationRepositoryCustom.java
  src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoLocationRepositoryImpl.java
  src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoRepository.java
  src/main/java/com/example/namo2/domain/memo/domain/MoimMemo.java
  src/main/java/com/example/namo2/domain/memo/domain/MoimMemoLocation.java
  src/main/java/com/example/namo2/domain/memo/domain/MoimMemoLocationAndUser.java
  src/main/java/com/example/namo2/domain/memo/domain/MoimMemoLocationImg.java
  src/main/java/com/example/namo2/domain/memo/ui/MoimMemoController.java
  src/main/java/com/example/namo2/domain/memo/ui/dto/MoimMemoRequest.java
  src/main/java/com/example/namo2/domain/memo/ui/dto/MoimMemoResponse.java
  src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java
  src/main/java/com/example/namo2/domain/moim/application/MoimScheduleFacade.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleAndUserService.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleService.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimService.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimAndUserRepository.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleAndUserRepository.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleAndUserRepositoryCustom.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleAndUserRepositoryImpl.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleRepository.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleRepositoryCustom.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleRepositoryImpl.java
  src/main/java/com/example/namo2/domain/moim/domain/MoimAndUser.java
  src/main/java/com/example/namo2/domain/moim/domain/MoimSchedule.java
  src/main/java/com/example/namo2/domain/moim/domain/MoimScheduleAndUser.java
  src/main/java/com/example/namo2/domain/moim/ui/MoimController.java
  src/main/java/com/example/namo2/domain/moim/ui/MoimScheduleController.java
  src/main/java/com/example/namo2/domain/moim/ui/dto/LocationInfo.java
  src/main/java/com/example/namo2/domain/moim/ui/dto/MoimMemoDto.java
  src/main/java/com/example/namo2/domain/moim/ui/dto/MoimMemoLocationDto.java
  src/main/java/com/example/namo2/domain/moim/ui/dto/MoimMemoReq.java
  src/main/java/com/example/namo2/domain/moim/ui/dto/MoimUserDto.java
  src/main/java/com/example/namo2/domain/schedule/application/ScheduleFacade.java
  src/main/java/com/example/namo2/domain/schedule/application/converter/ImageConverter.java
  src/main/java/com/example/namo2/domain/schedule/application/converter/ScheduleResponseConverter.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/AlarmService.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/ImageService.java
  src/main/java/com/example/namo2/domain/schedule/dao/repository/ImageRepositoryImpl.java
  src/main/java/com/example/namo2/domain/schedule/dao/repository/ScheduleRepositoryCustom.java
  src/main/java/com/example/namo2/domain/schedule/dao/repository/ScheduleRepositoryImpl.java
  src/main/java/com/example/namo2/domain/schedule/domain/Alarm.java
  src/main/java/com/example/namo2/domain/schedule/domain/Image.java
  src/main/java/com/example/namo2/domain/schedule/ui/dto/DiaryDto.java
  src/main/java/com/example/namo2/domain/schedule/ui/dto/SliceDiaryDto.java
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
  src/main/java/com/example/namo2/global/utils/apple/AppleAuthClient.java
Labels: :recycle: refactor

#34 [Feature/27] pr assignees와 reviewer 할당 자동화
  .github/CODEOWNERS
  .github/workflows/pr-assigner.yml
Labels: :sparkles: feature, :wrench: chore

#41 [Feature/37] 약관 동의 API 추가
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/domain/user/application/converter/TermConverter.java
  src/main/java/com/example/namo2/domain/user/application/impl/UserService.java
  src/main/java/com/example/namo2/domain/user/dao/repository/TermRepository.java
  src/main/java/com/example/namo2/domain/user/domain/Content.java
  src/main/java/com/example/namo2/domain/user/domain/Term.java
  src/main/java/com/example/namo2/domain/user/ui/UserController.java
  src/main/java/com/example/namo2/domain/user/ui/dto/UserRequest.java
  src/main/java/com/example/namo2/global/common/entity/BaseTimeEntity.java
  src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
Labels: :sparkles: feature

#45 [Feature/44]모임 참가 API Response 수정
  src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java
  src/main/java/com/example/namo2/domain/moim/application/converter/MoimResponseConverter.java
  src/main/java/com/example/namo2/domain/moim/ui/MoimController.java
  src/main/java/com/example/namo2/domain/moim/ui/dto/MoimResponse.java
Labels: :recycle: refactor

#43 [Feature/38] 모임 일정 전체 조회 API 추가
  src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java
  src/main/java/com/example/namo2/domain/moim/application/MoimScheduleFacade.java
  src/main/java/com/example/namo2/domain/moim/application/converter/MoimScheduleResponseConverter.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleService.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleAndUserRepositoryImpl.java
  src/main/java/com/example/namo2/domain/moim/ui/MoimScheduleController.java
Labels: :sparkles: feature

#51 [Feature/42] 모임 스케줄 및 모임 메모 삭제 로직 리팩토링
  src/main/java/com/example/namo2/domain/memo/application/MoimMemoFacade.java
  src/main/java/com/example/namo2/domain/memo/application/impl/MoimMemoLocationService.java
  src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoLocationRepository.java
  src/main/java/com/example/namo2/domain/memo/ui/MoimMemoController.java
  src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java
  src/main/java/com/example/namo2/domain/moim/application/MoimScheduleFacade.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleAndUserService.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleService.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleRepository.java
  src/main/java/com/example/namo2/domain/moim/domain/MoimSchedule.java
  src/main/java/com/example/namo2/domain/moim/domain/MoimScheduleStatus.java
  src/main/java/com/example/namo2/domain/schedule/application/ScheduleFacade.java
Labels: :sparkles: feature, :recycle: refactor

#54 [Feature/40] 소셜로그인 회원 탈퇴
  .gitignore
  build.gradle
  src/main/java/com/example/namo2/Namo2Application.java
  src/main/java/com/example/namo2/domain/category/application/impl/CategoryService.java
  src/main/java/com/example/namo2/domain/category/dao/repository/CategoryRepository.java
  src/main/java/com/example/namo2/domain/memo/application/impl/MoimMemoLocationService.java
  src/main/java/com/example/namo2/domain/memo/dao/repository/MoimMemoLocationAndUserRepository.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimAndUserService.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimScheduleAndUserService.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimService.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimAndUserRepository.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimScheduleAndUserRepository.java
  src/main/java/com/example/namo2/domain/schedule/application/ScheduleFacade.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/AlarmService.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/ImageService.java
  src/main/java/com/example/namo2/domain/schedule/application/impl/ScheduleService.java
  src/main/java/com/example/namo2/domain/schedule/dao/repository/AlarmRepository.java
  src/main/java/com/example/namo2/domain/schedule/dao/repository/ScheduleRepository.java
  src/main/java/com/example/namo2/domain/schedule/ui/ScheduleController.java
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/domain/user/application/converter/UserConverter.java
  src/main/java/com/example/namo2/domain/user/application/impl/UserService.java
  src/main/java/com/example/namo2/domain/user/dao/repository/TermRepository.java
  src/main/java/com/example/namo2/domain/user/dao/repository/UserRepository.java
  src/main/java/com/example/namo2/domain/user/domain/Content.java
  src/main/java/com/example/namo2/domain/user/domain/Term.java
  src/main/java/com/example/namo2/domain/user/domain/User.java
  src/main/java/com/example/namo2/domain/user/domain/UserStatus.java
  src/main/java/com/example/namo2/domain/user/ui/AuthController.java
  src/main/java/com/example/namo2/domain/user/ui/UserController.java
  src/main/java/com/example/namo2/domain/user/ui/dto/UserRequest.java
  src/main/java/com/example/namo2/global/common/entity/BaseTimeEntity.java
  src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
  src/main/java/com/example/namo2/global/config/properties/FeignConfig.java
  src/main/java/com/example/namo2/global/config/properties/JpaAuditingConfig.java
  src/main/java/com/example/namo2/global/config/properties/SchedulingConfig.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleAuthApi.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleAuthClient.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleFeignConfiguration.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleFeignException.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleProperties.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleResponse.java
  src/main/java/com/example/namo2/global/feignclient/apple/AppleResponseConverter.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoAuthApi.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoAuthClient.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoFeignClientExceptionDecoder.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoFeignConfiguration.java
  src/main/java/com/example/namo2/global/feignclient/kakao/KakaoResponse.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverAuthApi.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverAuthClient.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverFeignConfiguration.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverFeignException.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverOpenApi.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverProperties.java
  src/main/java/com/example/namo2/global/feignclient/naver/NaverResponse.java
  src/main/java/com/example/namo2/global/utils/apple/AppleAuthApi.java
  src/main/java/com/example/namo2/global/utils/apple/AppleResponse.java
  src/main/resources/application-auth.yml
Labels: :sparkles: feature

#57 [Feature/53] Docker file 작성 및 build
  .gitignore
  Dockerfile
  build.gradle
  src/main/resources/application-dev.yml
Labels: :sparkles: feature, :building_construction: build, :construction_worker: ci/cd, :wrench: chore

#52 [Feature/48] 카테고리 validation 검증 로직 및 비기능 개발
  src/main/java/com/example/namo2/domain/category/application/CategoryFacade.java
  src/main/java/com/example/namo2/domain/category/application/converter/CategoryConverter.java
  src/main/java/com/example/namo2/domain/category/application/impl/CategoryService.java
  src/main/java/com/example/namo2/domain/category/dao/repository/CategoryRepository.java
  src/main/java/com/example/namo2/domain/category/dao/repository/CategoryRepositoryCustom.java
  src/main/java/com/example/namo2/domain/category/dao/repository/CategoryRepositoryImpl.java
  src/main/java/com/example/namo2/domain/category/domain/Category.java
  src/main/java/com/example/namo2/domain/category/domain/CategoryKind.java
  src/main/java/com/example/namo2/domain/category/ui/CategoryController.java
  src/main/java/com/example/namo2/domain/category/ui/dto/CategoryRequest.java
  src/main/java/com/example/namo2/domain/category/validation/annotation/CategoryName.java
  src/main/java/com/example/namo2/domain/category/validation/validator/CategoryValidator.java
  src/main/java/com/example/namo2/domain/user/application/UserFacade.java
  src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
  src/main/java/com/example/namo2/global/utils/SocialUtils.java
Labels: :bug: bug, :recycle: refactor

#56 [Feature/49] 모임 Validation 검증 로직 및 비기능 개발
  src/main/java/com/example/namo2/domain/moim/application/MoimFacade.java
  src/main/java/com/example/namo2/domain/moim/application/MoimScheduleFacade.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimAndUserService.java
  src/main/java/com/example/namo2/domain/moim/application/impl/MoimService.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimAndUserRepository.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimRepository.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimRepositoryCustom.java
  src/main/java/com/example/namo2/domain/moim/dao/repository/MoimRepositoryImpl.java
  src/main/java/com/example/namo2/domain/moim/domain/Moim.java
  src/main/java/com/example/namo2/domain/moim/domain/MoimStatus.java
  src/main/java/com/example/namo2/domain/moim/ui/MoimController.java
  src/main/java/com/example/namo2/domain/moim/ui/dto/MoimRequest.java
  src/main/java/com/example/namo2/global/common/response/BaseResponseStatus.java
  src/main/resources/application-aws.yml
Labels: :bug: bug, :recycle: refactor

#67 [Feature/59] Request, Response Logging Filter 구현
  src/main/java/com/example/namo2/domain/test/TestController.java
  src/main/java/com/example/namo2/domain/test/ui/TestController.java
  src/main/java/com/example/namo2/domain/test/ui/dto/TestRequest.java
  src/main/java/com/example/namo2/domain/test/ui/dto/TestResponse.java
  src/main/java/com/example/namo2/global/logging/filter/ApiLoggingFilter.java
  src/main/resources/application-dev.yml
Labels: :sparkles: feature, :wrench: chore
