Repository Namo-log/Server, pull requests merged in 2024-07, with the labels that each got.

#162 [Feature/153] 스프링 시큐리티 적용
  application/external-api/build.gradle
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/controller/GroupController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/controller/GroupDiaryController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/controller/GroupScheduleController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/controller/CategoryController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/controller/DiaryController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/controller/ScheduleController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/controller/TermController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/facade/UserFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/service/UserService.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/authentication/CustomGrantedAuthority.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/authentication/SecurityUserDetails.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/authentication/SecurityUserDetailsService.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/filter/JwtAuthenticationFilter.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/filter/JwtExceptionFilter.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/handler/JwtAccessDeniedHandler.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/handler/JwtAuthenticationEntryPoint.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/jwt/access/AccessTokenProvider.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/common/security/jwt/refresh/RefreshTokenProvider.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/interceptor/AuthenticationInterceptor.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/interceptor/InterceptorConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/properties/PropertiesConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/CorsConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/MethodSecurityConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/SecurityAdapterConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/SecurityAuthConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/SecurityConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/SecurityFilterConfig.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/security/WebSecurityUrl.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/config/web/CorsFilter.java
  application/external-api/src/main/java/com/namo/spring/application/external/global/utils/JwtUtils.java
  application/external-api/src/main/resources/auth.yml
  core/core-common/build.gradle
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  core/core-common/src/main/java/com/namo/spring/core/common/exception/JwtException.java
  core/core-common/src/main/java/com/namo/spring/core/common/utils/JwtErrorCodeUtil.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/properties/ServerDomainProperties.java
  core/core-infra/src/main/resources/aws.yml
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/domains/user/domain/User.java
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/domains/user/type/UserRole.java
  storage/db-mysql/src/main/resources/db/migration/V1.0.1__Add_user_role_column_to_user_table.sql
Labels: :sparkles: feature

#172 [Feature/167] 이미지 리사이징 적용
  core/core-infra/build.gradle
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/aws/s3/FileUtils.java
Labels: :sparkles: feature, :building_construction: build, :wrench: chore, :recycle: refactor

#176 [Feature/175] db-mysql-v2 모듈 생성
  settings.gradle
  storage/db-mysql-v2/build.gradle
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/DomainPackageLocation.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/MysqlApplication.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/common/converter/AbstractEnumAttributeConverter.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/common/converter/CodedEnum.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/common/model/BaseTimeEntity.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/common/utils/CodedEnumConverterUtil.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/config/JpaConfig.java
  storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/JpaPackageLocation.java
  storage/db-mysql-v2/src/main/resources/mysql.yml
  storage/db-mysql-v2/src/test/java/com/namo/spring/db/mysql/config/MysqlContainerTest.java
  storage/db-mysql-v2/src/test/java/com/namo/spring/db/mysql/config/MysqlTestContainerConfig.java
Labels: :sparkles: feature

#182 [Bug/158] (개인) 일정 기록 수정 API 버그 수정
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/controller/DiaryController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/facade/DiaryFacade.java
Labels: :bug: bug, :sparkles: feature, :recycle: refactor

#185 [Refactor/184] 개인 일정 기록 전체 조회 Response 리팩토링
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/converter/DiaryResponseConverter.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/dto/DiaryResponse.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/service/ScheduleService.java
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/domains/individual/repository/schedule/ScheduleRepository.java
Labels: :bug: bug, :recycle: refactor

#191 :bug: Fix: flyway enabled false
  storage/db-mysql-v2/src/main/resources/mysql.yml
Labels: :bug: bug

#198 [Style/197] DTO, Controller 정리
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/controller/GroupDiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/controller/GroupScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/controller/MeetingActivityController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/controller/MeetingDiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/controller/MeetingScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/dto/GroupDiaryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/dto/GroupRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/dto/GroupScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/dto/MeetingActivityResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/dto/MeetingDiaryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/dto/MeetingScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/dto/MeetingScheduleResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/individual/controller/CategoryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/individual/controller/DiaryController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/individual/controller/ScheduleController.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/individual/dto/CategoryRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/individual/dto/CategoryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/individual/dto/DiaryResponse.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/individual/dto/ScheduleRequest.java
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/individual/dto/ScheduleResponse.java
Labels: :art: style, :recycle: refactor

#196 Refactor/195
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/converter/GroupDiaryResponseConverter.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/dto/GroupDiaryResponse.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/dto/MeetingDiaryResponse.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/converter/ScheduleResponseConverter.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/dto/ScheduleResponse.java
Labels: :art: style, :recycle: refactor

#214 [Refactor] 개인 기록, 모임 기록 수정 로직 변경
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/controller/MeetingDiaryController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/controller/TempMeetingDiaryController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/dto/MeetingDiaryRequest.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/facade/MeetingDiaryFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/service/GroupActivityService.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/individual/controller/DiaryController.java
Labels: :bug: bug, :recycle: refactor

#217 [Feature/213] Auth Api 문서 보완
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/api/AuthApi.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/controller/AuthController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/dto/UserRequest.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/facade/UserFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/user/service/UserService.java
Labels: :recycle: refactor

#226 [Feature/224] 네임 규칙 적용 전/후의 MeetingSchedule API 문서 보완
  application/external-api-v2/src/main/java/com/namo/spring/application/external/api/group/controller/MeetingScheduleController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/api/MeetingScheduleApi.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/api/TempMeetingScheduleApi.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/controller/MeetingScheduleController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/controller/TempMeetingScheduleController.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/converter/GroupScheduleResponseConverter.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/converter/MeetingScheduleResponseConverter.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/dto/GroupScheduleRequest.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/dto/GroupScheduleResponse.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/dto/MeetingScheduleRequest.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/dto/MeetingScheduleResponse.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/facade/MeetingScheduleFacade.java
  application/external-api/src/main/java/com/namo/spring/application/external/api/group/service/GroupAndUserService.java
  core/core-common/src/main/java/com/namo/spring/core/common/code/status/ErrorStatus.java
  core/core-common/src/main/java/com/namo/spring/core/common/utils/DateUtil.java
  core/core-infra/src/main/java/com/namo/spring/core/infra/common/aws/s3/FileUtils.java
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/domains/group/repository/group/MoimAndUserRepository.java
  storage/db-mysql/src/main/java/com/namo/spring/db/mysql/domains/individual/type/Period.java
Labels: :recycle: refactor
